version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - public
      - todo_net

networks:
  public:
  todo_net: